version: '3.9'

services:
  victim:
    build: victim/
    cap_add:
      - NET_ADMIN
    networks:
      tcpdump_network:
        ipv4_address: 192.168.1.10
  attacker:
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      tcpdump_network:
        ipv4_address: 192.168.1.11

networks:
  tcpdump_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
    driver_opts:
      com.docker.network.bridge.name: br_tcpdump

