version: '3.9'

services:
  tcpdump:
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      tcpdump_network:
        ipv4_address: 192.168.1.10

networks:
  tcpdump_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

